inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    # Generated files.
    - 'lib/google/**/*'

Style/GlobalVars:
  AllowedVariables:
    - $log

# TODO: Re-enable this and fix frozen strings.
Style/FrozenStringLiteralComment:
  Enabled: false
