language: ruby
sudo: false
rvm:
  - 2.5
  - 2.4
  - 2.3.1
script: "bundle exec rake"
before_install:
 - gem update bundler
notifications:
  email:
    recipients:
      - google-fluentd-notifications+travis@google.com
    on_success: change
    on_failure: change
