# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/logging/v1/log_entry.proto

require 'google/protobuf'

require 'google/logging/type/http_request_pb'
require 'google/logging/type/log_severity_pb'
require 'google/protobuf/any_pb'
require 'google/protobuf/struct_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.logging.v1.LogEntry" do
    optional :metadata, :message, 1, "google.logging.v1.LogEntryMetadata"
    optional :insert_id, :string, 4
    optional :log, :string, 5
    optional :http_request, :message, 7, "google.logging.type.HttpRequest"
    optional :operation, :message, 8, "google.logging.v1.LogEntryOperation"
    optional :writer_email_address, :string, 9
    oneof :payload do
      optional :proto_payload, :message, 2, "google.protobuf.Any"
      optional :text_payload, :string, 3
      optional :struct_payload, :message, 6, "google.protobuf.Struct"
    end
  end
  add_message "google.logging.v1.LogEntryMetadata" do
    optional :timestamp, :message, 9, "google.protobuf.Timestamp"
    optional :severity, :enum, 2, "google.logging.type.LogSeverity"
    optional :project_id, :string, 3
    optional :project_number, :int64, 10
    optional :service_name, :string, 4
    optional :region, :string, 5
    optional :zone, :string, 6
    optional :user_id, :string, 7
    map :labels, :string, :string, 8
  end
  add_message "google.logging.v1.LogEntryOperation" do
    optional :id, :string, 1
    optional :producer, :string, 2
    optional :first, :bool, 3
    optional :last, :bool, 4
  end
end

module Google
  module Logging
    module V1
      LogEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.logging.v1.LogEntry").msgclass
      LogEntryMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.logging.v1.LogEntryMetadata").msgclass
      LogEntryOperation = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.logging.v1.LogEntryOperation").msgclass
    end
  end
end
